### ISSUE TITLE
Suggestion: Timer

### ISSUE THREAD

**Issue by urbknu** [sirjorj/xhud#10]
As a user of xhud, I want to set, start, pause and clear a timer, in order to display the countdown in the hud during match

**Comment by sirjorj** [comment]
This one is probably not going to happen, and mainly for technical reasons.  Xhud generates an image and when the streaming software (usually OBS) notices that the file changed on disk, it is smart enough to reload the image.  There is a noticeable delay before the reload, and it tends to vary.  Occasionally updating the gamestate is no big deal, but refeshing the image every second would not look good.
Unless i can find a better way to get the image into OBS (if there was a framebuffer API or something, that would be cool, and allow for animations), showing a timer will not be something that xhud does.

**Comment by urbknu** [comment]
Sounds right. Closing the issue.
