### ISSUE TITLE
As an user I want to add more info about the stream

### ISSUE THREAD

**Issue by s4ndm4ns** [sirjorj/xhud#11]
Id like to be able to add event name that willl show on top
on a bar in center, same font and size as player names, with same background

**Comment by sirjorj** [comment]
For something like this, I would say just make your own image and add it to the scene on OBS (or whatever streaming software you use).  I don't this this needs to be a part of xhud.  If matching the font is the important thing, the fonts are included with the program - just install them to your system and have at it.

**Comment by sirjorj** [comment]
I've been thinking about this and am warming up to the idea.  Allowing a simple one like title like "Whatever Open - Swiss R3" or "Somewhere Story Tourney - Top 8" could be useful and shouldn't be too hard to add.  I will probably restrict length like squad names, as in, just cut it off when it doesnt fit anymore.  I might work on it this evening on twitch.  Also, I created a twitter account for xhud stuff so if you have an account, follow @xhudoverlay for updates.

I will almost certainly not add a feature to include the streamers logo - THAT is something you can just add to the scene!

**Comment by sirjorj** [comment]
Just pushed this to master.  add a "run.title" setting to your settings file like this:

run.title=This Is My Title

At some point I will make this configurable in-game but the parser currently treats spaces as delimiters so a command cannot have a space.  This is a throwback to the original version of the parser.  The newer regex-based one can probably be made smarter to handle this by making the regex expressions handle the spaces.  Until then, use the settings file.

**Comment by sirjorj** [comment]
New builds are uploaded
