### ISSUE TITLE
Ion missles do not validate

### ISSUE THREAD

**Issue by s4ndm4ns** [sirjorj/xhud#12]
Ion missles do not validate

**Comment by s4ndm4ns** [comment]
"name": "quickdraw",
            "ship": "tiesffighter",
            "points": 32,
            "upgrades": {
                "missile": [
                    "ionpulsemissiles"

**Comment by s4ndm4ns** [comment]
{"description":"","faction":"rebel","name":"Unnamed Squadron","pilots":[{"name":"prototypepilot","points":20,"ship":"awing","upgrades":{"missile":["ionpulsemissiles"]}}],"points":20,"

**Comment by sirjorj** [comment]
Good find.  I had it entered as "ionpulsemissile" instead of "ionpulsemissiles".  It is fixed in the source but I won't get a new build out for a bit.  I just played in an x-wing regional today and fixed this from the model room and am very tired!  :)

**Comment by sirjorj** [comment]
Latest build fixes this.
