### ISSUE TITLE
Option to generate individual images for each squad

### ISSUE THREAD

**Issue by urbknu** [sirjorj/xhud#2]
Hi, 
Wondering if it can be possible to add an option to generate an individual image for each squad. Makes it easier to reposition and scale the images to fit the stream. I thought this was possible before?

Great overlay, thank you.

**Comment by sirjorj** [comment]
It was possible before.  I though combining them into a single image made it easier.  I will make it an option in the next release.

**Comment by sirjorj** [comment]
I just committed some changes to master that add this as an option.  There is a new v0.6+ on the build page as well.
If you have a ~/.xhud.conf file that contains the line "run.multiimage=yes", it assumes the output path is a dir and creates p1.png and p2.png there.  Also, you can add the line "run.outfile=XXX" (where XXX is the outdir name) to that conf file and then you dont have to specify the outdir every time you run it.
Thanks for using xhud and let me know if you stream with it - I'd love to see it in action!

**Comment by urbknu** [comment]
Thank you! This worked very well
It however seems that the score has vanished? 
Would it be possible to get the score as a third image? 
or possibly pushed to a text file?

**Comment by sirjorj** [comment]
I switched to single-image output to let me do more things such as MOV score, dice results (it's there but I want to clean up the commands for it), and maybe even card pop-ups at some point.
Having separate images makes this all a lot more work on my end (writing to separate files) and on the users' end (having to add multiple things to the overlay).
Having separate images for all these things is a possibility, but probably not something I will do in the near future.  The text file is an interesting idea as well.  I want to put more thought into this before I commit to anything, but I like the idea.

**Comment by urbknu** [comment]
the MOV, and dice where a very nice addition to the hud. Card pop-up would be genius, especially for crits. The biggest challenge with the single images setup was the size of the list - as it took up quite a bit of space. Having said that, I could possibly crop the single image into multiple images in OBS. If that works, then the image and its features can be cropped to anyones taste.

**Comment by sirjorj** [comment]
Showing face-up damage conditions is definitely on my to-do list.

Another thing was putting colored numbers by each ship (red for p1, blue for p2, or maybe something you could tweak in your settings file).  Then either generate matching images for each number for people who want to track the ships closer.  Or just do the first part and let them make their own text labels to put over the ships.  Or just let them make their own text labels for both! :)
