### ISSUE TITLE
Maul crew with Ezra on Rebel faction raises warning

### ISSUE THREAD

**Issue by urbknu** [sirjorj/xhud#3]
When running Maul in a rebel list with Ezra, xhud raises a warning. Not something grave, as the list shows regardless.

**Example**
{"faction":"rebel",,"pilots":[{"name":"zeborrelios","points":18,"ship":"attackshuttle","upgrades":{"crew":["chopper"],"title":["phantom"]}},{"name":"fennrau","points":20,"ship":"sheathipedeclassshuttle","upgrades":{"amd":["flightassistastromech"],"crew":["hotshotcopilot"],"ept":["veteraninstincts"]}},{"name":"lothalrebel","points":35,"ship":"vcx100","upgrades":{"crew":["ezrabridger","maul"],"mod":["engineupgrade"],"system":["sensorjammer"],"title":["ghost"],"turret":["twinlaserturret"]}}],"points":99,"version":"4.2.0"}

**Comment by sirjorj** [comment]
Good find.  I didn't fully implement the validation for Maul.  Working on it (live on twitch!) now.
