### ISSUE TITLE
Trouble with loading specific list

### ISSUE THREAD

**Issue by urbknu** [sirjorj/xhud#5]
Having trouble loading a specific list. The list validates in other builders, so i am not quite sure what is wrong with this list in xhud. 

**Xhud is throwing the following exception**
> Checking lists...
> libc++abi.dylib: terminating with uncaught exception of type SquadNotFound: Squad not found: './test.json'
>   ./test.json - Abort trap: 6

**List xws**
```
 {
  "description": "",
  "name": "",
  "faction": "scum",
  "pilots": [{
    "name": "bobafett",
    "points": 50,
    "ship": "firespray31",
    "upgrades": {
      "ept": ["fearlessness"],
      "crew": ["hotshotcopilot"],
      "illicit": ["feedbackarray"],
      "mod": ["engineupgrade"],
      "title": ["slavei"]
    }
  }, {
    "name": "asajjventress",
    "points": 50,
    "ship": "lancerclasspursuitcraft",
    "upgrades": {
      "ept": ["veteraninstincts"],
      "crew": ["lattsrazzi"],
      "illicit": ["feedbackarray", "glitterstim"],
      "mod": ["countermeasures"],
      "title": ["shadowcaster"]
    }
  }],
  "points": 100,
  "vendor": {
    "yasb": {
      "builder": "(Yet Another) X-Wing Miniatures Squad Builder",
      "builder_url": "https://geordanr.github.io/xwing/",
      "link": "https://geordanr.github.io/xwing/?f=Scum%20and%20Villainy&d=v4!s!116:188,-1,-1,213,-1,112:1:3:U.-1;219:27,190,112,128:44:12:&sn=Unnamed%20Squadron&obs="
    }
  },
  "version": "0.3.0"
} 
```

**Comment by urbknu** [comment]
The issue seems to be related to the Slave 1 title. I havn't quite figured out why though.

**Comment by sirjorj** [comment]
Good find - these are exactly the type of issues that I want to track down.  The issue here is that it should be entered as "slavei" and not "slave1" like I have it.  I also am working to make it so errors like this will point out exactly which pilot or upgrade it choked on.

Thanks for helping out with this!

**Comment by sirjorj** [comment]
I just uploaded a new build
