### ISSUE TITLE
Suggestion: Make pilot inactive when all hull has been removed

### ISSUE THREAD

**Issue by urbknu** [sirjorj/xhud#6]
As a xhud user, I want a pilot to become inactive when i have removed all the hull, in order to avoid having to run two commands when a ship is destroyed

**Comment by sirjorj** [comment]
I have definitely considered this, but shot it down as I don't want this program to be too 'smart' - i want to make it a 'it does what you tell it to' and not 'it automatically does other things when you do some things'.  However, I do like the idea of 'autodisable' being a setting so you could enable that if you want.  I might look into that this evening.

**Comment by urbknu** [comment]
I like the idea of not intruding to much into the users management of the hud, but in the case of the hull being removed there is no more pilot. A setting to make this an option would be a neat solution.

**Comment by sirjorj** [comment]
run.autodisable=yes will give you that behavior now :)
