### ISSUE TITLE
Bug: special characters push the faction logo and text down

### ISSUE THREAD

**Issue by urbknu** [sirjorj/xhud#7]
In Norway we use the special character "Å" in names. The distortion is most likely due to the ring above the A makes this a tall character. A possible fix is to have a static position for the name regardless of height?

**Å character**
![image](https://user-images.githubusercontent.com/5707221/36753766-7828dbf8-1c07-11e8-8f30-f7854281c54b.png)

**A character**
![image](https://user-images.githubusercontent.com/5707221/36753717-5614570e-1c07-11e8-9f26-88360bcae784.png)

**Comment by sirjorj** [comment]
Thanks again for coming up with use cases that I have not encountered!  Font rendering is tricky.  I don't remember off hand how I am positioning that title but I will look into it this evening.  I will copy/paste those characters into the name of a squad and see what I can do.

**Comment by urbknu** [comment]
This is a real corner case, which i doubt will be very relevant in 99% of the cases, but there might be other international characters that can provoke the same behavior in the name field.

**Comment by urbknu** [comment]
I was thinking there might be some other cases where this could happen, as there are many special characters out there. So i had a look at the font characters and compared them all with the letter A

![image](https://user-images.githubusercontent.com/5707221/36754919-c22daff0-1c0a-11e8-9afb-81aa403b9b23.png)

**Comment by urbknu** [comment]
Special character Ÿ
![image](https://user-images.githubusercontent.com/5707221/36755005-0ffeb5e4-1c0b-11e8-9f09-44aa7fb1428e.png)

Normal Y
![image](https://user-images.githubusercontent.com/5707221/36755020-1e93c36a-1c0b-11e8-9285-839cec1b69eb.png)

**Comment by sirjorj** [comment]
Yeah, due to the (stupid) way I was calculating the location for the glyph, the size of the title affected it.  I fixed it.  (currently live on twitch)
