### ISSUE TITLE
Suggestion: Change player name from center alignment to left alignment

### ISSUE THREAD

**Issue by urbknu** [sirjorj/xhud#8]
As an xhud user, I would prefer to have player name left aligned instead of center aligned, in order to avoid name overlapping the faction logo and loose the first name. 

Centered long name:
![image](https://user-images.githubusercontent.com/5707221/36753319-19c963bc-1c06-11e8-8be9-5ff45c7dd0a3.png)

**Comment by sirjorj** [comment]
Good point.  That should be an easy fix.
Also, the "As an xhud user" openings tell me you work in software development too! :)

**Comment by sirjorj** [comment]
This is fixed.  The name is still centered, but if the name is too long, it will just cut off the end so it doesnt spill past the boundaries.  This was a known issue (even had a comment that I need to address it!) but should be fine now.
